package main

import (
	"fmt"
	"io"
)

// RouterWriteExtensionGuide prints a detailed authoring guide for router extensions.
func RouterWriteExtensionGuide(writer io.Writer) error {
	lines := []string{
		"Router extension authoring guide:",
		"",
		"When to use this:",
		"  - Use an optional capability extension when the feature adds cross-cutting infrastructure and boot should continue if it fails.",
		"  - Wire optional capability extensions through `internal/router/ext/optional_extensions.go`.",
		"  - Place the extension package in `internal/router/ext/extensions/<name>/`.",
		"",
		"Working pattern:",
		"  1. Add a dedicated port with `wrlk add --name <PortName> --value <port-value>`.",
		"  2. Define or extend the router-native capability contract in `internal/router/capabilities/` so consumers resolve a stable semantic interface, not a concrete extension type.",
		"  3. Scaffold the optional extension with `wrlk ext add --name <name>`.",
		"  4. Implement the provider inside `internal/router/ext/extensions/<name>/` and register it from `RouterProvideRegistration`.",
		"  5. Keep `Provides()` exactly aligned with the port you register.",
		"  6. Keep `Consumes()` truthful; if the extension needs another port at boot, declare it there.",
		"  7. Document the extension in `doc.go` so `wrlk guide current` can surface what it does and how to consume it.",
		"",
		"Worked example: go-pretty CLI styling capability",
		"  Goal: expose a reusable table-rendering capability to the app without hard-coding `go-pretty` into unrelated packages.",
		"",
		"  Step 1: add the port",
		"    `go run ./internal/router/tools/wrlk add --name PortCLIStyle --value cli-style`",
		"",
		"  Step 2: add the capability contract",
		"    Extend `internal/router/capabilities/cli.go` with the semantic kinds and interface methods the app should resolve.",
		"    The app resolves by `router.PortCLIStyle` through `capabilities.ResolveCLIOutputStyler()`.",
		"    Names such as `header`, `info`, `success`, `warning`, `error`, `table.normal`, and `layout.panel` are canonical semantic roles owned by the router contract.",
		"    If a library uses different style headers or option names, convert to them inside the extension instead of leaking those names to consumers.",
		"",
		"  Step 3: scaffold the optional extension",
		"    `go run ./internal/router/tools/wrlk ext add --name prettystyle`",
		"",
		"  Step 4: implement the provider in `internal/router/ext/extensions/prettystyle/`",
		"    - Add any renderer dependency to the extension only, never to the router core.",
		"    - Create a provider type that satisfies `capabilities.CLIOutputStyler`.",
		"    - Convert canonical router capability roles into the renderer's established patterns inside the extension.",
		"    - Build text, table, and layout output inside the provider, not in the consumer.",
		"",
		"  Step 5: register it from the extension",
		"    Required() should return false.",
		"    Consumes() should return nil unless the formatter needs another router capability at boot.",
		"    Provides() should return `[]router.PortName{router.PortCLIStyle}`.",
		"    RouterProvideRegistration should instantiate the provider and call `reg.RouterRegisterProvider(router.PortCLIStyle, provider)`.",
		"",
		"  Step 6: consume it from the app",
		"    Resolve the provider with `capabilities.ResolveCLIOutputStyler()`.",
		"    If the port is missing, degrade gracefully because this is an optional capability extension.",
		"",
		"Worked example: Charm CLI chrome and interaction capability",
		"  Goal: expose semantic text/layout chrome plus prompts without hard-coding `huh` or `lipgloss` into consumers.",
		"",
		"  Step 1: add the chrome and interaction ports",
		"    `go run ./internal/router/tools/wrlk add --name PortCLIChrome --value cli-chrome`",
		"    `go run ./internal/router/tools/wrlk add --name PortCLIInteraction --value cli-interaction`",
		"",
		"  Step 2: extend the capability contract",
		"    Add chrome layout kinds such as `layout.panel`, `layout.split`, and `layout.gutter`.",
		"    Add prompt kinds such as `prompt.select`, `prompt.toggle`, `prompt.confirm`, and `prompt.input`.",
		"    Resolve the chrome capability through `capabilities.ResolveCLIChromeStyler()`.",
		"    Resolve the capability through `capabilities.ResolveCLIInteractor()`.",
		"",
		"  Step 3: scaffold the optional extension",
		"    `go run ./internal/router/tools/wrlk ext add --name charmcli`",
		"",
		"  Step 4: implement the provider in `internal/router/ext/extensions/charmcli/`",
		"    - Map semantic text and layout kinds onto `lipgloss` helpers inside the extension.",
		"    - Map semantic prompt kinds onto `huh` components inside the extension.",
		"    - Use `lipgloss` only inside the extension for prompt presentation details.",
		"",
		"  Step 5: register it from the extension",
		"    Provides() should return `[]router.PortName{router.PortCLIChrome, router.PortCLIInteraction}`.",
		"    RouterProvideRegistration should call `reg.RouterRegisterProvider(router.PortCLIChrome, provider)`.",
		"    RouterProvideRegistration should call `reg.RouterRegisterProvider(router.PortCLIInteraction, provider)`.",
		"",
		"Rules that keep the extension usable by the app:",
		"  - The router port is the discovery key.",
		"  - The interface in `internal/router/capabilities/` is the app contract.",
		"  - The extension package owns the concrete implementation details.",
		"  - Canonical capability names stay in the router contract; the extension translates them to library-specific style names or options.",
		"  - Consumers must never import the concrete extension package just to use the capability.",
		"  - Optional extensions should return warnings on boot failure, not take down the app.",
		"",
		"Verification loop:",
		"  - `go run ./internal/router/tools/wrlk guide current`",
		"  - `go run ./internal/router/tools/wrlk lock verify`",
		"  - Boot the app and resolve the port from one real consumer path.",
		"",
		"Reference doc:",
		"  - `docs/documentation/extensions.md`",
	}

	for _, line := range lines {
		if _, err := fmt.Fprintln(writer, line); err != nil {
			return fmt.Errorf("write extension guide line: %w", err)
		}
	}

	return nil
}
